# Generated by Django 4.2.21 on 2025-06-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='deactivation_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
